### ISSUE TITLE
Crash while editing the hand playing a given note

### ISSUE THREAD

**Issue by evernost** [evernost/gangQin#4]
Title: Rachmaninoff, Piano Concerto 2, first movement.
At location 2219, the score is incorrect: the right hand is supposed to play the chord.
Editing the hand of the first note of the chord is OK, but editing the second will make it crash.

```
Traceback (most recent call last):
  File "c:\Users\quent\Documents\recherche\gangQin\src\main.py", line 628, in <module>
    userScore.switchHand(fingerSelWidget.getEditedNote())
  File "c:\Users\quent\Documents\recherche\gangQin\src\score.py", line 618, in switchHand
    self.cursorsLeft.remove(self.cursor)
ValueError: list.remove(x): x not in list
```

![image](https://github.com/user-attachments/assets/bf849e3a-0a23-4464-af55-884c1144609c)
_Picture right before the crash_

**Comment by evernost** [comment]
Fixed in v1.3
